version: "3.9"

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot-data:/bot/data
    environment:
      - DB_PATH=/bot/data/bot.db
