package localization

import "fmt"

type langMap map[string]string

var strings = map[string]langMap{
	"en": {
		"welcome":          "Welcome to %s!\n\nI am a modern Telegram bot with inline menus, customizable settings, and more. Use the buttons below to get started.\n\n👑 Owner: %s",
		"help":             "Here are the things I can do:\n\n/start - Show main menu\n/help - This help message\n/settings - Customize your experience\n/profile - View your profile\n/feedback - Send us feedback\n/about - Learn about this bot\n/poll - Create a quick poll\n/tiktok - Download TikTok videos\n/fb - Download Facebook videos\n/pin - Download Pinterest videos\n/sc - Download Snapchat stories/spotlight\n/tw - Download Twitter/X posts\n/bing - Search the web or find images",
		"mainMenu":         "Main Menu",
		"settings":         "⚙️ Settings\n\nCustomize your experience:",
		"languageChanged":  "Language changed to %s.",
		"profile":          "👤 Your Profile\n\nUser ID: %d\nName: %s\nLanguage: %s\nJoined: %s",
		"feedbackPrompt":   "💬 Send your feedback\n\nType your message below. Your feedback helps us improve!",
		"feedbackReceived": "✅ Thank you for your feedback! We appreciate it.",
		"about":            "ℹ️ About %s\n\nVersion: %s\nDescription: %s\n👑 Owner: %s (%s)\n🕐 Timezone: %s\n\nBuilt with ❤️ using Go and go-telegram-bot-api",
		"pollQuestion":     "📊 Send me a question for the poll:",
		"pollOptions":      "Send me the options, one per line (min 2, max 10):",
		"pollCreated":      "✅ Poll created!",
		"adminPanel":       "🔐 Admin Panel\n\nTotal users: %d\nTotal feedback: %d",
		"noPermission":     "⛔ You do not have permission to use this command.",
		"unknownCommand":   "Unknown command. Use /help to see available commands.",
		"backToMenu":       "« Back to Main Menu",
		"settingsMenu":     "⚙️ Settings",
		"language":         "🌐 Language",
		"notifications":    "🔔 Notifications",
		"close":            "❌ Close",
		"selectLanguage":   "Select your preferred language:",
		"error":            "⚠️ An error occurred. Please try again later.",
		"processing":       "⏳ Processing...",
		"notifOnAlert":     "Notifications enabled",
		"notifOffAlert":    "Notifications disabled",
		"notifStatus":      "Notifications: %s",
		"notifEnabled":     "🔔 Enabled",
		"notifDisabled":    "🔕 Disabled",
		"confirmAction":    "✅ Action confirmed!",
		"cancelAction":     "❌ Action cancelled.",
		"confirmedAlert":   "Confirmed ✅",
		"cancelledAlert":   "Cancelled ❌",
		"closedAlert":      "Closed",
		"confirmed":        "✅ Confirmed!",
		"cancelled":        "❌ Cancelled.",
		"ytPrompt":         "📥 Send me a YouTube URL to download:",
		"ytInvalid":        "⚠️ Invalid YouTube URL. Please send a valid YouTube link.",
		"ytFormat":         "🎯 Select format:",
		"ytDownloading":    "⏳ Downloading your video, please wait...",
		"ytUploading":      "📤 Uploading your file to Telegram...",
		"ytSuccess":        "✅ Download complete!",
		"ytError":          "❌ Download failed. The video may be unavailable or restricted.",
		"ytFormatMp3":      "🎵 MP3 Audio",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Send me an Instagram post/reel URL to download:",
		"igInvalid":        "⚠️ Invalid Instagram URL. Please send a valid Instagram link.",
		"igDownloading":    "⏳ Downloading your Instagram content, please wait...",
		"igUploading":      "📤 Uploading your file to Telegram...",
		"igSuccess":        "✅ Download complete!",
		"igError":          "❌ Download failed. The post may be private or unavailable.",
		"ttPrompt":         "📱 Send me a TikTok video URL to download:",
		"ttInvalid":        "⚠️ Invalid TikTok URL. Please send a valid TikTok link.",
		"ttFormat":         "🎯 Select download format:",
		"ttFormatWM":       "🎬 With Watermark",
		"ttFormatNoWM":     "🎬 No Watermark",
		"ttFormatHD":       "🎬 HD No Watermark",
		"ttFormatMusic":    "🎵 Music Audio",
		"ttDownloading":    "⏳ Downloading your TikTok video, please wait...",
		"ttUploading":      "📤 Uploading your file to Telegram...",
		"ttSuccess":        "✅ Download complete!",
		"ttError":          "❌ Download failed. The video may be unavailable.",
		"fbPrompt":         "📘 Send me a Facebook video URL to download:",
		"fbInvalid":        "⚠️ Invalid Facebook URL. Please send a valid Facebook video link.",
		"fbFormat":         "🎯 Select quality:",
		"fbDownloading":    "⏳ Downloading your Facebook video, please wait...",
		"fbUploading":      "📤 Uploading your file to Telegram...",
		"fbSuccess":        "✅ Download complete!",
		"fbError":          "❌ Download failed. The video may be unavailable.",
		"pinPrompt":        "📌 Send me a Pinterest video URL to download:",
		"pinInvalid":       "⚠️ Invalid Pinterest URL. Please send a valid Pinterest link.",
		"pinDownloading":   "⏳ Downloading your Pinterest content, please wait...",
		"pinUploading":     "📤 Uploading your file to Telegram...",
		"pinSuccess":       "✅ Download complete!",
		"pinError":         "❌ Download failed. The pin may be unavailable.",
		"scPrompt":         "👻 Send me a Snapchat story/spotlight URL to download:",
		"scInvalid":        "⚠️ Invalid Snapchat URL. Please send a valid Snapchat link.",
		"scDownloading":    "⏳ Downloading your Snapchat content, please wait...",
		"scFormat":         "👻 Multiple snaps found. Choose which to download:",
		"scUploading":      "📤 Uploading your file to Telegram...",
		"scSuccess":       "✅ Download complete!",
		"scError":         "❌ Download failed. The snap may be unavailable.",
		"twPrompt":        "🐦 Send me a Twitter/X post URL to download:",
		"twInvalid":       "⚠️ Invalid Twitter URL. Please send a valid Twitter/X link.",
		"twDownloading":   "⏳ Downloading your Twitter content, please wait...",
		"twUploading":     "📤 Uploading your file to Telegram...",
		"twSuccess":       "✅ Download complete!",
		"twError":         "❌ Download failed. The tweet may be unavailable.",
		"bingPrompt":      "🔍 Choose search type:",
		"bingSearch":      "🔍 Web Search",
		"bingImages":      "🖼️ Image Search",
		"bingQuery":       "Send me your search query:",
		"bingNoResults":   "No results found for your query.",
		"bingCount":       "How many images to send?",
		"bingCount1":      "1",
		"bingCount5":      "5",
		"bingCount10":     "10",
		"bingCountAll":    "All",
		"bingSending":     "📤 Sending images...",
		"bingSuccess":     "✅ Sent %d images.",
		"bingError":       "❌ Search failed. Please try again.",
		"searchMenu":      "🔍 Search Options",
		"searchPin":       "📌 Pinterest Search",
		"pinSearchPrompt": "📌 Send me a Pinterest search query:",
		"pinSearchCount":  "How many images to send?",
		"pinSearchSending":"📤 Sending Pinterest images...",
		"pinSearchSuccess":"✅ Sent %d Pinterest images.",
		"pinSearchError":  "❌ Pinterest search failed.",
		"searchSticker":   "🎨 Sticker Search",
		"stickerPrompt":   "🎨 Send me a sticker search query:",
		"stickerCount":    "How many stickers to send?",
		"stickerSending":  "📤 Sending stickers...",
		"stickerSuccess":  "✅ Sent %d stickers.",
		"stickerError":    "❌ Sticker search failed.",
		"searchImgur":     "🖼️ Imgur Search",
		"imgurPrompt":     "🖼️ Send me an Imgur search query:",
		"imgurCount":      "How many images to send?",
		"imgurSending":    "📤 Sending images...",
		"imgurSuccess":    "✅ Sent %d images.",
		"imgurError":      "❌ Imgur search failed.",
		"searchYt":        "🎬 YouTube Search",
		"ytSearchPrompt":  "🎬 Send me a YouTube search query:",
		"ytSearchError":   "❌ YouTube search failed.",
		"textMaker":       "🎨 Text Maker",
		"textMakerMenu":   "🎨 Text Maker",
		"textPro":         "✨ TextPro",
		"textProPrompt":   "✍️ Send me the text for TextPro:",
		"textProSending":  "🎨 Generating text art...",
		"textProSuccess":  "✅ Text art generated!",
		"textProError":    "❌ TextPro failed.",
		"backToTextMaker": "« Back to Text Maker",
	},
	"es": {
		"welcome":          "¡Bienvenido a %s!\n\nSoy un bot moderno de Telegram con menús en línea, ajustes personalizables y más. Usa los botones de abajo para empezar.\n\n👑 Dueño: %s",
		"help":             "Aquí están las cosas que puedo hacer:\n\n/start - Mostrar menú principal\n/help - Este mensaje de ayuda\n/settings - Personalizar tu experiencia\n/profile - Ver tu perfil\n/feedback - Envíanos comentarios\n/about - Información sobre este bot\n/poll - Crear una encuesta rápida",
		"mainMenu":         "Menú Principal",
		"settings":         "⚙️ Ajustes\n\nPersonaliza tu experiencia:",
		"languageChanged":  "Idioma cambiado a %s.",
		"profile":          "👤 Tu Perfil\n\nID de usuario: %d\nNombre: %s\nIdioma: %s\nRegistrado: %s",
		"feedbackPrompt":   "💬 Envía tus comentarios\n\nEscribe tu mensaje a continuación. ¡Tus comentarios nos ayudan a mejorar!",
		"feedbackReceived": "✅ ¡Gracias por tus comentarios! Los apreciamos.",
		"about":            "ℹ️ Acerca de %s\n\nVersión: %s\nDescripción: %s\n👑 Dueño: %s (%s)\n🕐 Zona horaria: %s\n\nConstruido con ❤️ usando Go y go-telegram-bot-api",
		"pollQuestion":     "📊 Envíame una pregunta para la encuesta:",
		"pollOptions":      "Envíame las opciones, una por línea (mín 2, máx 10):",
		"pollCreated":      "✅ ¡Encuesta creada!",
		"adminPanel":       "🔐 Panel de Administración\n\nUsuarios totales: %d\nComentarios totales: %d",
		"noPermission":     "⛔ No tienes permiso para usar este comando.",
		"unknownCommand":   "Comando desconocido. Usa /help para ver los comandos disponibles.",
		"backToMenu":       "« Volver al Menú Principal",
		"settingsMenu":     "⚙️ Ajustes",
		"language":         "🌐 Idioma",
		"notifications":    "🔔 Notificaciones",
		"close":            "❌ Cerrar",
		"selectLanguage":   "Selecciona tu idioma preferido:",
		"error":            "⚠️ Ocurrió un error. Inténtalo de nuevo más tarde.",
		"processing":       "⏳ Procesando...",
		"notifOnAlert":     "Notificaciones activadas",
		"notifOffAlert":    "Notificaciones desactivadas",
		"notifStatus":      "Notificaciones: %s",
		"notifEnabled":     "🔔 Activadas",
		"notifDisabled":    "🔕 Desactivadas",
		"confirmAction":    "✅ ¡Acción confirmada!",
		"cancelAction":     "❌ Acción cancelada.",
		"confirmedAlert":   "Confirmado ✅",
		"cancelledAlert":   "Cancelado ❌",
		"closedAlert":      "Cerrado",
		"confirmed":        "✅ ¡Confirmado!",
		"cancelled":        "❌ Cancelado.",
		"ytPrompt":         "📥 Envíame una URL de YouTube para descargar:",
		"ytInvalid":        "⚠️ URL de YouTube no válida. Por favor, envía un enlace de YouTube válido.",
		"ytFormat":         "🎯 Selecciona formato:",
		"ytDownloading":    "⏳ Descargando tu video, por favor espera...",
		"ytUploading":      "📤 Subiendo tu archivo a Telegram...",
		"ytSuccess":        "✅ ¡Descarga completa!",
		"ytError":          "❌ Descarga fallida. El video puede no estar disponible o estar restringido.",
		"ytFormatMp3":      "🎵 Audio MP3",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Envíame una URL de Instagram (post/reel) para descargar:",
		"igInvalid":        "⚠️ URL de Instagram no válida. Por favor, envía un enlace de Instagram válido.",
		"igDownloading":    "⏳ Descargando tu contenido de Instagram, por favor espera...",
		"igUploading":      "📤 Subiendo tu archivo a Telegram...",
		"igSuccess":        "✅ ¡Descarga completa!",
		"igError":          "❌ Descarga fallida. La publicación puede ser privada o no estar disponible.",
	},
	"fr": {
		"welcome":          "Bienvenue sur %s!\n\nJe suis un bot Telegram moderne avec des menus en ligne, des paramètres personnalisables et plus encore. Utilisez les boutons ci-dessous pour commencer.\n\n👑 Propriétaire: %s",
		"help":             "Voici ce que je peux faire :\n\n/start - Afficher le menu principal\n/help - Ce message d'aide\n/settings - Personnaliser votre expérience\n/profile - Voir votre profil\n/feedback - Envoyez-nous des commentaires\n/about - En savoir plus sur ce bot\n/poll - Créer un sondage rapide",
		"mainMenu":         "Menu Principal",
		"settings":         "⚙️ Paramètres\n\nPersonnalisez votre expérience :",
		"languageChanged":  "Langue changée en %s.",
		"profile":          "👤 Votre Profil\n\nID utilisateur : %d\nNom : %s\nLangue : %s\nInscrit : %s",
		"feedbackPrompt":   "💬 Envoyez vos commentaires\n\nTapez votre message ci-dessous. Vos commentaires nous aident à nous améliorer !",
		"feedbackReceived": "✅ Merci pour vos commentaires ! Nous les apprécions.",
		"about":            "ℹ️ À propos de %s\n\nVersion : %s\nDescription : %s\n👑 Propriétaire: %s (%s)\n🕐 Fuseau horaire: %s\n\nConstruit avec ❤️ en utilisant Go et go-telegram-bot-api",
		"pollQuestion":     "📊 Envoyez-moi une question pour le sondage :",
		"pollOptions":      "Envoyez-moi les options, une par ligne (min 2, max 10) :",
		"pollCreated":      "✅ Sondage créé !",
		"adminPanel":       "🔐 Panneau d'Administration\n\nUtilisateurs totaux : %d\nCommentaires totaux : %d",
		"noPermission":     "⛔ Vous n'avez pas la permission d'utiliser cette commande.",
		"unknownCommand":   "Commande inconnue. Utilisez /help pour voir les commandes disponibles.",
		"backToMenu":       "« Retour au Menu Principal",
		"settingsMenu":     "⚙️ Paramètres",
		"language":         "🌐 Langue",
		"notifications":    "🔔 Notifications",
		"close":            "❌ Fermer",
		"selectLanguage":   "Sélectionnez votre langue préférée :",
		"error":            "⚠️ Une erreur s'est produite. Veuillez réessayer plus tard.",
		"processing":       "⏳ Traitement en cours...",
		"notifOnAlert":     "Notifications activées",
		"notifOffAlert":    "Notifications désactivées",
		"notifStatus":      "Notifications : %s",
		"notifEnabled":     "🔔 Activées",
		"notifDisabled":    "🔕 Désactivées",
		"confirmAction":    "✅ Action confirmée !",
		"cancelAction":     "❌ Action annulée.",
		"confirmedAlert":   "Confirmé ✅",
		"cancelledAlert":   "Annulé ❌",
		"closedAlert":      "Fermé",
		"confirmed":        "✅ Confirmé !",
		"cancelled":        "❌ Annulé.",
		"ytPrompt":         "📥 Envoyez-moi une URL YouTube à télécharger :",
		"ytInvalid":        "⚠️ URL YouTube invalide. Veuillez envoyer un lien YouTube valide.",
		"ytFormat":         "🎯 Sélectionnez le format :",
		"ytDownloading":    "⏳ Téléchargement de votre vidéo, veuillez patienter...",
		"ytUploading":      "📤 Envoi de votre fichier vers Telegram...",
		"ytSuccess":        "✅ Téléchargement terminé !",
		"ytError":          "❌ Échec du téléchargement. La vidéo est peut-être indisponible ou restreinte.",
		"ytFormatMp3":      "🎵 Audio MP3",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Envoyez-moi une URL de publication/reel Instagram à télécharger :",
		"igInvalid":        "⚠️ URL Instagram invalide. Veuillez envoyer un lien Instagram valide.",
		"igDownloading":    "⏳ Téléchargement de votre contenu Instagram, veuillez patienter...",
		"igUploading":      "📤 Envoi de votre fichier vers Telegram...",
		"igSuccess":        "✅ Téléchargement terminé !",
		"igError":          "❌ Échec du téléchargement. La publication est peut-être privée ou indisponible.",
	},
	"de": {
		"welcome":          "Willkommen bei %s!\n\nIch bin ein moderner Telegram-Bot mit Inline-Menüs, anpassbaren Einstellungen und mehr. Benutze die Knöpfe unten, um zu starten.\n\n👑 Besitzer: %s",
		"help":             "Hier ist, was ich tun kann:\n\n/start - Hauptmenü anzeigen\n/help - Diese Hilfemeldung\n/settings - Deine Erfahrung anpassen\n/profile - Dein Profil anzeigen\n/feedback - Sende uns Feedback\n/about - Über diesen Bot\n/poll - Eine schnelle Umfrage erstellen",
		"mainMenu":         "Hauptmenü",
		"settings":         "⚙️ Einstellungen\n\nPasse deine Erfahrung an:",
		"languageChanged":  "Sprache geändert zu %s.",
		"profile":          "👤 Dein Profil\n\nBenutzer-ID: %d\nName: %s\nSprache: %s\nBeigetreten: %s",
		"feedbackPrompt":   "💬 Sende dein Feedback\n\nGib deine Nachricht unten ein. Dein Feedback hilft uns, besser zu werden!",
		"feedbackReceived": "✅ Vielen Dank für dein Feedback! Wir schätzen es sehr.",
		"about":            "ℹ️ Über %s\n\nVersion: %s\nBeschreibung: %s\n👑 Besitzer: %s (%s)\n🕐 Zeitzone: %s\n\nErstellt mit ❤️ mit Go und go-telegram-bot-api",
		"pollQuestion":     "📊 Sende mir eine Frage für die Umfrage:",
		"pollOptions":      "Sende mir die Optionen, eine pro Zeile (min 2, max 10):",
		"pollCreated":      "✅ Umfrage erstellt!",
		"adminPanel":       "🔐 Admin-Bereich\n\nBenutzer insgesamt: %d\nFeedback insgesamt: %d",
		"noPermission":     "⛔ Du hast keine Berechtigung, diesen Befehl zu verwenden.",
		"unknownCommand":   "Unbekannter Befehl. Benutze /help, um verfügbare Befehle zu sehen.",
		"backToMenu":       "« Zurück zum Hauptmenü",
		"settingsMenu":     "⚙️ Einstellungen",
		"language":         "🌐 Sprache",
		"notifications":    "🔔 Benachrichtigungen",
		"close":            "❌ Schließen",
		"selectLanguage":   "Wähle deine bevorzugte Sprache:",
		"error":            "⚠️ Ein Fehler ist aufgetreten. Bitte versuche es später erneut.",
		"processing":       "⏳ Verarbeitung...",
		"notifOnAlert":     "Benachrichtigungen aktiviert",
		"notifOffAlert":    "Benachrichtigungen deaktiviert",
		"notifStatus":      "Benachrichtigungen: %s",
		"notifEnabled":     "🔔 Aktiviert",
		"notifDisabled":    "🔕 Deaktiviert",
		"confirmAction":    "✅ Aktion bestätigt!",
		"cancelAction":     "❌ Aktion abgebrochen.",
		"confirmedAlert":   "Bestätigt ✅",
		"cancelledAlert":   "Abgebrochen ❌",
		"closedAlert":      "Geschlossen",
		"confirmed":        "✅ Bestätigt!",
		"cancelled":        "❌ Abgebrochen.",
		"ytPrompt":         "📥 Sende mir eine YouTube-URL zum Herunterladen:",
		"ytInvalid":        "⚠️ Ungültige YouTube-URL. Bitte sende einen gültigen YouTube-Link.",
		"ytFormat":         "🎯 Format auswählen:",
		"ytDownloading":    "⏳ Video wird heruntergeladen, bitte warten...",
		"ytUploading":      "📤 Datei wird zu Telegram hochgeladen...",
		"ytSuccess":        "✅ Download abgeschlossen!",
		"ytError":          "❌ Download fehlgeschlagen. Das Video ist möglicherweise nicht verfügbar oder eingeschränkt.",
		"ytFormatMp3":      "🎵 MP3-Audio",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Sende mir eine Instagram-Post/Reel-URL zum Herunterladen:",
		"igInvalid":        "⚠️ Ungültige Instagram-URL. Bitte sende einen gültigen Instagram-Link.",
		"igDownloading":    "⏳ Dein Instagram-Inhalt wird heruntergeladen, bitte warten...",
		"igUploading":      "📤 Datei wird zu Telegram hochgeladen...",
		"igSuccess":        "✅ Download abgeschlossen!",
		"igError":          "❌ Download fehlgeschlagen. Der Beitrag ist möglicherweise privat oder nicht verfügbar.",
	},
	"hi": {
		"welcome":          "स्वागत है %s में!\n\nमैं एक आधुनिक Telegram बॉट हूँ जिसमें इनलाइन मेनू, अनुकूलन योग्य सेटिंग्स और बहुत कुछ है। आरंभ करने के लिए नीचे दिए गए बटन का उपयोग करें।\n\n👑 मालिक: %s",
		"help":             "ये रही मेरी क्षमताएँ:\n\n/start - मुख्य मेनू दिखाएँ\n/help - यह सहायता संदेश\n/settings - अपना अनुभव अनुकूलित करें\n/profile - अपनी प्रोफ़ाइल देखें\n/feedback - हमें प्रतिक्रिया भेजें\n/about - इस बॉट के बारे में जानें\n/poll - एक त्वरित मतदान बनाएँ",
		"mainMenu":         "मुख्य मेनू",
		"settings":         "⚙️ सेटिंग्स\n\nअपना अनुभव अनुकूलित करें:",
		"languageChanged":  "भाषा बदलकर %s कर दी गई।",
		"profile":          "👤 आपकी प्रोफ़ाइल\n\nउपयोगकर्ता ID: %d\nनाम: %s\nभाषा: %s\nशामिल हुए: %s",
		"feedbackPrompt":   "💬 अपनी प्रतिक्रिया भेजें\n\nअपना संदेश नीचे टाइप करें। आपकी प्रतिक्रिया से हमें सुधार करने में मदद मिलती है!",
		"feedbackReceived": "✅ आपकी प्रतिक्रिया के लिए धन्यवाद! हम इसकी सराहना करते हैं।",
		"about":            "ℹ️ %s के बारे में\n\nसंस्करण: %s\nविवरण: %s\n👑 मालिक: %s (%s)\n🕐 समय क्षेत्र: %s\n\n❤️ के साथ Go और go-telegram-bot-api का उपयोग करके बनाया गया",
		"pollQuestion":     "📊 मुझे मतदान के लिए एक प्रश्न भेजें:",
		"pollOptions":      "विकल्प भेजें, एक प्रति पंक्ति (न्यूनतम 2, अधिकतम 10):",
		"pollCreated":      "✅ मतदान बनाया गया!",
		"adminPanel":       "🔐 व्यवस्थापक पैनल\n\nकुल उपयोगकर्ता: %d\nकुल प्रतिक्रिया: %d",
		"noPermission":     "⛔ आपके पास इस कमांड का उपयोग करने की अनुमति नहीं है।",
		"unknownCommand":   "अज्ञात कमांड। उपलब्ध कमांड देखने के लिए /help का उपयोग करें।",
		"backToMenu":       "« मुख्य मेनू पर वापस",
		"settingsMenu":     "⚙️ सेटिंग्स",
		"language":         "🌐 भाषा",
		"notifications":    "🔔 सूचनाएँ",
		"close":            "❌ बंद करें",
		"selectLanguage":   "अपनी पसंदीदा भाषा चुनें:",
		"error":            "⚠️ एक त्रुटि हुई। कृपया बाद में पुनः प्रयास करें।",
		"processing":       "⏳ प्रसंस्करण हो रहा है...",
		"notifOnAlert":     "सूचनाएँ सक्षम",
		"notifOffAlert":    "सूचनाएँ अक्षम",
		"notifStatus":      "सूचनाएँ: %s",
		"notifEnabled":     "🔔 सक्षम",
		"notifDisabled":    "🔕 अक्षम",
		"confirmAction":    "✅ कार्रवाई की पुष्टि हो गई!",
		"cancelAction":     "❌ कार्रवाई रद्द कर दी गई।",
		"confirmedAlert":   "पुष्टि हुई ✅",
		"cancelledAlert":   "रद्द किया गया ❌",
		"closedAlert":      "बंद किया गया",
		"confirmed":        "✅ पुष्टि हो गई!",
		"cancelled":        "❌ रद्द कर दिया गया।",
		"ytPrompt":         "📥 मुझे डाउनलोड करने के लिए एक YouTube URL भेजें:",
		"ytInvalid":        "⚠️ अमान्य YouTube URL। कृपया एक वैध YouTube लिंक भेजें।",
		"ytFormat":         "🎯 प्रारूप चुनें:",
		"ytDownloading":    "⏳ आपका वीडियो डाउनलोड हो रहा है, कृपया प्रतीक्षा करें...",
		"ytUploading":      "📤 आपकी फ़ाइल Telegram पर अपलोड हो रही है...",
		"ytSuccess":        "✅ डाउनलोड पूर्ण!",
		"ytError":          "❌ डाउनलोड विफल। वीडियो अनुपलब्ध या प्रतिबंधित हो सकता है।",
		"ytFormatMp3":      "🎵 MP3 ऑडियो",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 मुझे डाउनलोड करने के लिए एक Instagram पोस्ट/रील URL भेजें:",
		"igInvalid":        "⚠️ अमान्य Instagram URL। कृपया एक वैध Instagram लिंक भेजें।",
		"igDownloading":    "⏳ आपकी Instagram सामग्री डाउनलोड हो रही है, कृपया प्रतीक्षा करें...",
		"igUploading":      "📤 आपकी फ़ाइल Telegram पर अपलोड हो रही है...",
		"igSuccess":        "✅ डाउनलोड पूर्ण!",
		"igError":          "❌ डाउनलोड विफल। पोस्ट निजी या अनुपलब्ध हो सकती है।",
	},
	"ur": {
		"welcome":          "%s میں خوش آمدید!\n\nمیں ایک جدید Telegram بوٹ ہوں جس میں ان لائن مینوز، حسب ضرورت ترتیبات اور بہت کچھ ہے۔ شروع کرنے کے لیے نیچے دیئے گئے بٹنوں کا استعمال کریں۔\n\n👑 مالک: %s",
		"help":             "یہ رہی میری صلاحیتیں:\n\n/start - مرکزی مینو دکھائیں\n/help - یہ مدد کا پیغام\n/settings - اپنا تجربہ حسب ضرورت بنائیں\n/profile - اپنی پروفائل دیکھیں\n/feedback - ہمیں رائے بھیجیں\n/about - اس بوٹ کے بارے میں جانیں\n/poll - ایک فوری رائے شماری بنائیں",
		"mainMenu":         "مرکزی مینو",
		"settings":         "⚙️ ترتیبات\n\nاپنا تجربہ حسب ضرورت بنائیں:",
		"languageChanged":  "زبان تبدیل کر کے %s کر دی گئی۔",
		"profile":          "👤 آپ کی پروفائل\n\nصارف ID: %d\nنام: %s\nزبان: %s\nشامل ہوئے: %s",
		"feedbackPrompt":   "💬 اپنی رائے بھیجیں\n\nاپنا پیغام نیچے ٹائپ کریں۔ آپ کی رائے ہمیں بہتر بنانے میں مدد دیتی ہے!",
		"feedbackReceived": "✅ آپ کی رائے کے لیے شکریہ! ہم اس کی قدر کرتے ہیں۔",
		"about":            "ℹ️ %s کے بارے میں\n\nورژن: %s\nتفصیل: %s\n👑 مالک: %s (%s)\n🕐 ٹائم زون: %s\n\n❤️ کے ساتھ Go اور go-telegram-bot-api کا استعمال کر کے بنایا گیا",
		"pollQuestion":     "📊 مجھے رائے شماری کے لیے ایک سوال بھیجیں:",
		"pollOptions":      "اختیارات بھیجیں، ایک فی سطر (کم از کم 2، زیادہ سے زیادہ 10):",
		"pollCreated":      "✅ رائے شماری بن گئی!",
		"adminPanel":       "🔐 انتظامی پینل\n\nکل صارفین: %d\nکل آراء: %d",
		"noPermission":     "⛔ آپ کو اس کمانڈ کو استعمال کرنے کی اجازت نہیں ہے۔",
		"unknownCommand":   "نامعلوم کمانڈ۔ دستیاب کمانڈز دیکھنے کے لیے /help استعمال کریں۔",
		"backToMenu":       "« مرکزی مینو پر واپس",
		"settingsMenu":     "⚙️ ترتیبات",
		"language":         "🌐 زبان",
		"notifications":    "🔔 اطلاعات",
		"close":            "❌ بند کریں",
		"selectLanguage":   "اپنی پسندیدہ زبان منتخب کریں:",
		"error":            "⚠️ ایک خرابی پیش آگئی۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
		"processing":       "⏳ پروسیسنگ جاری ہے...",
		"notifOnAlert":     "اطلاعات فعال",
		"notifOffAlert":    "اطلاعات غیر فعال",
		"notifStatus":      "اطلاعات: %s",
		"notifEnabled":     "🔔 فعال",
		"notifDisabled":    "🔕 غیر فعال",
		"confirmAction":    "✅ کارروائی کی تصدیق ہو گئی!",
		"cancelAction":     "❌ کارروائی منسوخ کر دی گئی۔",
		"confirmedAlert":   "تصدیق شدہ ✅",
		"cancelledAlert":   "منسوخ شدہ ❌",
		"closedAlert":      "بند",
		"confirmed":        "✅ تصدیق ہو گئی!",
		"cancelled":        "❌ منسوخ کر دیا گیا۔",
		"ytPrompt":         "📥 مجھے ڈاؤن لوڈ کرنے کے لیے ایک YouTube URL بھیجیں:",
		"ytInvalid":        "⚠️ غلط YouTube URL۔ براہ کرم ایک درست YouTube لنک بھیجیں۔",
		"ytFormat":         "🎯 فارمیٹ منتخب کریں:",
		"ytDownloading":    "⏳ آپ کی ویڈیو ڈاؤن لوڈ ہو رہی ہے، براہ کرم انتظار کریں...",
		"ytUploading":      "📤 آپ کی فائل Telegram پر اپ لوڈ ہو رہی ہے...",
		"ytSuccess":        "✅ ڈاؤن لوڈ مکمل!",
		"ytError":          "❌ ڈاؤن لوڈ ناکام۔ ویڈیو دستیاب نہیں ہے یا پابندی شدہ ہو سکتی ہے۔",
		"ytFormatMp3":      "🎵 MP3 آڈیو",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 مجھے ڈاؤن لوڈ کرنے کے لیے Instagram پوسٹ/ریل URL بھیجیں:",
		"igInvalid":        "⚠️ غلط Instagram URL۔ براہ کرم ایک درست Instagram لنک بھیجیں۔",
		"igDownloading":    "⏳ آپ کا Instagram مواد ڈاؤن لوڈ ہو رہا ہے، براہ کرم انتظار کریں...",
		"igUploading":      "📤 آپ کی فائل Telegram پر اپ لوڈ ہو رہی ہے...",
		"igSuccess":        "✅ ڈاؤن لوڈ مکمل!",
		"igError":          "❌ ڈاؤن لوڈ ناکام۔ پوسٹ نجی یا دستیاب نہیں ہو سکتی۔",
	},
	"sw": {
		"welcome":          "Karibu %s!\n\nMimi ni bot ya kisasa ya Telegram yenye menyu za ndani, mipangilio inayoweza kubadilishwa, na zaidi. Tumia vitufe vilivyo chini kuanza.\n\n👑 Mmiliki: %s",
		"help":             "Hivi ndivyo ninavyoweza kukusaidia:\n\n/start - Onyesha menyu kuu\n/help - Ujumbe huu wa usaidizi\n/settings - Badilisha mipangilio yako\n/profile - Tazama wasifu wako\n/feedback - Tuma maoni yako\n/about - Jifunze kuhusu bot hii\n/poll - Unda kura ya haraka",
		"mainMenu":         "Menyu Kuu",
		"settings":         "⚙️ Mipangilio\n\nBadilisha uzoefu wako:",
		"languageChanged":  "Lugha imebadilishwa kuwa %s.",
		"profile":          "👤 Wasifu Wako\n\nKitambulisho: %d\nJina: %s\nLugha: %s\nUmejiunga: %s",
		"feedbackPrompt":   "💬 Tuma maoni yako\n\nAndika ujumbe wako hapa chini. Maoni yako yanatusaidia kuboresha!",
		"feedbackReceived": "✅ Asante kwa maoni yako! Tunayashukuru.",
		"about":            "ℹ️ Kuhusu %s\n\nToleo: %s\nMaelezo: %s\n👑 Mmiliki: %s (%s)\n🕐 Saa za eneo: %s\n\nImetengenezwa kwa ❤️ kwa kutumia Go na go-telegram-bot-api",
		"pollQuestion":     "📊 Nitumie swali la kura:",
		"pollOptions":      "Tuma chaguzi, moja kwa mstari (angalau 2, zaidi ya 10):",
		"pollCreated":      "✅ Kura imeundwa!",
		"adminPanel":       "🔐 Paneli ya Wasimamizi\n\nJumla ya watumiaji: %d\nJumla ya maoni: %d",
		"noPermission":     "⛔ Huna ruhusa ya kutumia amri hii.",
		"unknownCommand":   "Amri haijulikani. Tumia /help kuona amri zinazopatikana.",
		"backToMenu":       "« Rudi kwenye Menyu Kuu",
		"settingsMenu":     "⚙️ Mipangilio",
		"language":         "🌐 Lugha",
		"notifications":    "🔔 Arifa",
		"close":            "❌ Funga",
		"selectLanguage":   "Chagua lugha unayopendelea:",
		"error":            "⚠️ Hitilafu imetokea. Tafadhali jaribu tena baadaye.",
		"processing":       "⏳ Inashughulikia...",
		"notifOnAlert":     "Arifa zimewashwa",
		"notifOffAlert":    "Arifa zimezimwa",
		"notifStatus":      "Arifa: %s",
		"notifEnabled":     "🔔 Zimewashwa",
		"notifDisabled":    "🔕 Zimezimwa",
		"confirmAction":    "✅ Hatua imethibitishwa!",
		"cancelAction":     "❌ Hatua imefutwa.",
		"confirmedAlert":   "Imethibitishwa ✅",
		"cancelledAlert":   "Imeghairiwa ❌",
		"closedAlert":      "Imefungwa",
		"confirmed":        "✅ Imethibitishwa!",
		"cancelled":        "❌ Imeghairiwa.",
		"ytPrompt":         "📥 Nitumie URL ya YouTube kupakua:",
		"ytInvalid":        "⚠️ URL ya YouTube si sahihi. Tafadhali tuma kiungo halali cha YouTube.",
		"ytFormat":         "🎯 Chagua umbizo:",
		"ytDownloading":    "⏳ Inapakua video yako, tafadhali subiri...",
		"ytUploading":      "📤 Inapakia faili yako kwa Telegram...",
		"ytSuccess":        "✅ Upakuaji umekamilika!",
		"ytError":          "❌ Upakuaji umeshindwa. Video inaweza kuwa haipatikani au imezuiliwa.",
		"ytFormatMp3":      "🎵 Sauti ya MP3",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Nitumie URL ya Instagram post/reel kupakua:",
		"igInvalid":        "⚠️ URL ya Instagram si sahihi. Tafadhali tuma kiungo halali cha Instagram.",
		"igDownloading":    "⏳ Inapakua maudhui yako ya Instagram, tafadhali subiri...",
		"igUploading":      "📤 Inapakia faili yako kwa Telegram...",
		"igSuccess":        "✅ Upakuaji umekamilika!",
		"igError":          "❌ Upakuaji umeshindwa. Chapisho linaweza kuwa la faragha au halipatikani.",
	},
	"ha": {
		"welcome":          "Barka da zuwa %s!\n\nNi bot ɗin Telegram na zamani mai menus na ciki, saituna da za a iya gyara, da ƙari. Yi amfani da maɓallan da ke ƙasa don farawa.\n\n👑 Mai shi: %s",
		"help":             "Ga abubuwan da zan iya yi:\n\n/start - Nuna babban menu\n/help - Wannan saƙon taimako\n/settings - Gyara abubuwan da ka fi so\n/profile - Duba bayanan ka\n/feedback - Aiko mana ra'ayin ka\n/about - Koyi game da wannan bot\n/poll - Ƙirƙiri ƙuri'a mai sauri",
		"mainMenu":         "Babban Menu",
		"settings":         "⚙️ Saituna\n\nGyara abubuwan da ka fi so:",
		"languageChanged":  "An canza harshe zuwa %s.",
		"profile":          "👤 Bayanan Ka\n\nID na mai amfani: %d\nSuna: %s\nHarshe: %s\nShiga: %s",
		"feedbackPrompt":   "💬 Aiko ra'ayin ka\n\nRubuta saƙonka a ƙasa. Ra'ayin ka yana taimaka mana mu inganta!",
		"feedbackReceived": "✅ Na gode da ra'ayin ka! Mun yaba da shi.",
		"about":            "ℹ️ Game da %s\n\nSigar: %s\nBayanin: %s\n👑 Mai shi: %s (%s)\n🕐 Yankin lokaci: %s\n\nAn gina shi da ❤️ ta amfani da Go da go-telegram-bot-api",
		"pollQuestion":     "📊 Aiko min tambaya don ƙuri'a:",
		"pollOptions":      "Aiko zaɓuɓɓuka, ɗaya a kowane layi (aƙalla 2, mafi yawan 10):",
		"pollCreated":      "✅ An ƙirƙiri ƙuri'a!",
		"adminPanel":       "🔐 Kwamitin Gudanarwa\n\nJimlar masu amfani: %d\nJimlar ra'ayi: %d",
		"noPermission":     "⛔ Ba ka da izinin amfani da wannan umarni.",
		"unknownCommand":   "Umarnin da ba a sani ba. Yi amfani da /help don ganin umarnin da ke akwai.",
		"backToMenu":       "« Koma zuwa Babban Menu",
		"settingsMenu":     "⚙️ Saituna",
		"language":         "🌐 Harshe",
		"notifications":    "🔔 Sanarwa",
		"close":            "❌ Rufe",
		"selectLanguage":   "Zaɓi harshen da ka fi so:",
		"error":            "⚠️ Kuskure ya faru. Da fatan za a sake gwadawa daga baya.",
		"processing":       "⏳ Ana aiki...",
		"notifOnAlert":     "An kunna sanarwa",
		"notifOffAlert":    "An kashe sanarwa",
		"notifStatus":      "Sanarwa: %s",
		"notifEnabled":     "🔔 An kunna",
		"notifDisabled":    "🔕 An kashe",
		"confirmAction":    "✅ An tabbatar da aikin!",
		"cancelAction":     "❌ An soke aikin.",
		"confirmedAlert":   "An tabbatar ✅",
		"cancelledAlert":   "An soke ❌",
		"closedAlert":      "An rufe",
		"confirmed":        "✅ An tabbatar!",
		"cancelled":        "❌ An soke.",
		"ytPrompt":         "📥 Aiko min URL ɗin YouTube don saukewa:",
		"ytInvalid":        "⚠️ URL ɗin YouTube bai inganta ba. Da fatan za a aiko mahaɗin YouTube mai inganci.",
		"ytFormat":         "🎯 Zaɓi tsari:",
		"ytDownloading":    "⏳ Ana sauke bidiyon ku, da fatan za a jira...",
		"ytUploading":      "📤 Ana ɗora fayil ɗin ku zuwa Telegram...",
		"ytSuccess":        "✅ An gama saukewa!",
		"ytError":          "❌ Saukewa ya gaza. Bidiyon na iya zama baya samuwa ko an taƙaita shi.",
		"ytFormatMp3":      "🎵 Sautin MP3",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Aiko min URL ɗin Instagram post/reel don saukewa:",
		"igInvalid":        "⚠️ URL ɗin Instagram bai inganta ba. Da fatan za a aiko mahaɗin Instagram mai inganci.",
		"igDownloading":    "⏳ Ana sauke abun cikin Instagram ɗin ku, da fatan za a jira...",
		"igUploading":      "📤 Ana ɗora fayil ɗin ku zuwa Telegram...",
		"igSuccess":        "✅ An gama saukewa!",
		"igError":          "❌ Saukewa ya gaza. Wataƙila sakon na sirri ne ko ba ya samuwa.",
	},
	"yo": {
		"welcome":          "Kaabo si %s!\n\nMo jẹ́ bot Telegram òde-òní pẹ̀lú àtọ̀jọ̀ inú, àwọn ètò tó ṣeé ṣàtúnṣe, àti púpọ̀ sí i. Lo àwọn bọ́tìnnì ní ìsàlẹ̀ láti bẹ̀rẹ̀.\n\n👑 Olówó: %s",
		"help":             "Àwọn nǹkan tí mo lè ṣe nìyí:\n\n/start - Fi àkọ́kọ́ àtọ̀jọ̀ hàn\n/help - Ifiranṣẹ ìrànwọ́ yìí\n/settings - Ṣàtúnṣe ìrírí rẹ\n/profile - Wo profaịlì rẹ\n/feedback - Rán àríwísí sí wa\n/about - Kọ́ nípa bot yìí\n/poll - Ṣẹ̀dá ìdìbò kan",
		"mainMenu":         "Àkọ́kọ́ Àtọ̀jọ̀",
		"settings":         "⚙️ Àwọn Ètò\n\nṢàtúnṣe ìrírí rẹ:",
		"languageChanged":  "Èdè yípadà sí %s.",
		"profile":          "👤 Profaịlì Rẹ\n\nID olumulo: %d\nOrúkọ: %s\nÈdè: %s\nDarapọ̀: %s",
		"feedbackPrompt":   "💬 Fi àríwísí rẹ ránsẹ́\n\nTẹ ifiranṣẹ rẹ sí àyè ìsàlẹ̀. Àríwísí rẹ ń ran wa lọ́wọ́ láti dára sí i!",
		"feedbackReceived": "✅ Mo dúpẹ́ fún àríwísí rẹ! A mọyè rẹ̀.",
		"about":            "ℹ️ Nípa %s\n\nẸ̀yà: %s\nÀpèjúwe: %s\n👑 Olówó: %s (%s)\n🕐 Agbègbè àkókò: %s\n\nTi a fi ❤️ kọ́ pẹ̀lú Go àti go-telegram-bot-api",
		"pollQuestion":     "📊 Rán ìbéèrè fún ìdìbò sí mi:",
		"pollOptions":      "Rán àwọn ààyàn, ọ̀kan fún ìlà (kéré jù 2, púpọ̀ jù 10):",
		"pollCreated":      "✅ Ìdìbò ti dá!",
		"adminPanel":       "🔐 Ìgbìmọ̀ Alákóso\n\nÀpapọ̀ àwọn olumulo: %d\nÀpapọ̀ àríwísí: %d",
		"noPermission":     "⛔ Ò ní ẹ̀tọ́ láti lo pàṣẹ yìí.",
		"unknownCommand":   "Pàṣẹ àìmọ. Lo /help láti wo àwọn pàṣẹ tó wà.",
		"backToMenu":       "« Padà sí Àkọ́kọ́ Àtọ̀jọ̀",
		"settingsMenu":     "⚙️ Àwọn Ètò",
		"language":         "🌐 Èdè",
		"notifications":    "🔔 Àwọn ìfitoniléti",
		"close":            "❌ Pa",
		"selectLanguage":   "Yan èdè tí o fẹ́ràn:",
		"error":            "⚠️ Àsìse kan ṣẹlẹ̀. Jọ̀wọ́ gbìyànjú lẹ́ẹ̀kan sí i lẹ́yìnná.",
		"processing":       "⏳ Ń ṣiṣẹ́...",
		"notifOnAlert":     "Àwọn ìfitoniléti ti ṣiṣẹ́",
		"notifOffAlert":    "Àwọn ìfitoniléti ti dá",
		"notifStatus":      "Àwọn ìfitoniléti: %s",
		"notifEnabled":     "🔔 Ti ṣiṣẹ́",
		"notifDisabled":    "🔕 Ti dá",
		"confirmAction":    "✅ Ìgbésẹ̀ ti fi dá!",
		"cancelAction":     "❌ Ìgbésẹ̀ ti fagi lé.",
		"confirmedAlert":   "Ti fi dá ✅",
		"cancelledAlert":   "Ti fagi lé ❌",
		"closedAlert":      "Ti pa",
		"confirmed":        "✅ Ti fi dá!",
		"cancelled":        "❌ Ti fagi lé.",
		"ytPrompt":         "📥 Rán URL YouTube sí mi láti gba lati ayelujara:",
		"ytInvalid":        "⚠️ URL YouTube ti kò wulo. Jọ̀wọ́ fi ọ̀rọ̀ asopọ̀ YouTube tí ó wúlò ránṣẹ́.",
		"ytFormat":         "🎯 Yan ọna kika:",
		"ytDownloading":    "⏳ Gbigba fidio rẹ lati ayelujara, jọ̀wọ́ duro...",
		"ytUploading":      "📤 Gbigbe faili rẹ soke si Telegram...",
		"ytSuccess":        "✅ Gbigba lati ayelujara ti pari!",
		"ytError":          "❌ Gbigba lati ayelujara kuna. Fidio le ma wa tabi ni ihamọ.",
		"ytFormatMp3":      "🎵 MP3 Ohun",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Rán URL Instagram post/reel sí mi láti gba lati ayelujara:",
		"igInvalid":        "⚠️ URL Instagram ti kò wulo. Jọ̀wọ́ fi ọ̀rọ̀ asopọ̀ Instagram tí ó wúlò ránṣẹ́.",
		"igDownloading":    "⏳ Gbigba akoonu Instagram rẹ lati ayelujara, jọ̀wọ́ duro...",
		"igUploading":      "📤 Gbigbe faili rẹ soke si Telegram...",
		"igSuccess":        "✅ Gbigba lati ayelujara ti pari!",
		"igError":          "❌ Gbigba lati ayelujara kuna. Ifiweranṣẹ le jẹ ikọkọ tabi ko si.",
	},
	"zu": {
		"welcome":          "Siyakwemukela ku %s!\n\nNgiyi-bot ye-Telegram yesimanje enamamenyu angaphakathi, izilungiselelo ezilungisekayo, nokunye okuningi. Sebenzisa izinkinobho ezingezansi ukuze uqale.\n\n👑 Umnikazi: %s",
		"help":             "Nansi into engingayenza:\n\n/start - Khombisa imenyu enkulu\n/help - Lo mlayezi wosizo\n/settings - Lungiselela ulwazi lwakho\n/profile - Buka iphrofayili yakho\n/feedback - Thumela impendulo yakho kithi\n/about - Funda ngale bot\n/poll - Dala inhlolovo esheshayo",
		"mainMenu":         "Imenyu Enkulu",
		"settings":         "⚙️ Izilungiselelo\n\nLungiselela ulwazi lwakho:",
		"languageChanged":  "Ulimi lushintshiwe lwaba %s.",
		"profile":          "👤 Iphrofayili Yakho\n\nID yomsebenzisi: %d\nIgama: %s\nUlimi: %s\nUjoyine: %s",
		"feedbackPrompt":   "💬 Thumela impendulo yakho\n\nBhala umlayezo wakho ngezansi. Impendulo yakho isisiza sithuthuke!",
		"feedbackReceived": "✅ Siyabonga ngempendulo yakho! Siyayazisa.",
		"about":            "ℹ️ Mayelana %s\n\nInguqulo: %s\nIncazelo: %s\n👑 Umnikazi: %s (%s)\n🕐 Isifunda sesikhathi: %s\n\nYakhiwe ngo❤️ kusetshenziswa Go ne-go-telegram-bot-api",
		"pollQuestion":     "📊 Ngithumele umbuzo wenhlolovo:",
		"pollOptions":      "Thumela izinketho, eyodwa emgqeni (okungenani 2, okuphezulu 10):",
		"pollCreated":      "✅ Inhlolovo idaliwe!",
		"adminPanel":       "🔐 Iphaneli Yabaphathi\n\nInani labasebenzisi: %d\nInani lempendulo: %d",
		"noPermission":     "⛔ Awunazo izimvume zokusebenzisa lo myalo.",
		"unknownCommand":   "Umyalo ongaziwa. Sebenzisa /help ukubona imiyalo etholakalayo.",
		"backToMenu":       "« Buyela Emenyu Enkulu",
		"settingsMenu":     "⚙️ Izilungiselelo",
		"language":         "🌐 Ulimi",
		"notifications":    "🔔 Izaziso",
		"close":            "❌ Vala",
		"selectLanguage":   "Khetha ulimi oluthandayo:",
		"error":            "⚠️ Kwenzeka iphutha. Sicela uzame futhi kamuva.",
		"processing":       "⏳ Iyacubungula...",
		"notifOnAlert":     "Izaziso zivuliwe",
		"notifOffAlert":    "Izaziso zivaliwe",
		"notifStatus":      "Izaziso: %s",
		"notifEnabled":     "🔔 Zivuliwe",
		"notifDisabled":    "🔕 Zivaliwe",
		"confirmAction":    "✅ Isenzo siqinisekisiwe!",
		"cancelAction":     "❌ Isenzo sikhanseliwe.",
		"confirmedAlert":   "Kuqinisekisiwe ✅",
		"cancelledAlert":   "Kukhanseliwe ❌",
		"closedAlert":      "Kuvaliwe",
		"confirmed":        "✅ Kuqinisekisiwe!",
		"cancelled":        "❌ Kukhanseliwe.",
		"ytPrompt":         "📥 Ngithumele i-URL ye-YouTube ukuze ngilande:",
		"ytInvalid":        "⚠️ I-URL ye-YouTube ayivumelekile. Sicela uthumele isixhumanisi se-YouTube esivumelekile.",
		"ytFormat":         "🎯 Khetha ifomethi:",
		"ytDownloading":    "⏳ Ilanda ividiyo yakho, sicela ulinde...",
		"ytUploading":      "📤 Ilayisha ifayela lakho ku-Telegram...",
		"ytSuccess":        "✅ Ukulanda kuphothuliwe!",
		"ytError":          "❌ Ukulanda kwehlulekile. Ividiyo ingase ingatholakali noma ivinjelwe.",
		"ytFormatMp3":      "🎵 Umsindo we-MP3",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Ngithumele i-URL ye-Instagram post/reel ukuze ngilande:",
		"igInvalid":        "⚠️ I-URL ye-Instagram ayivumelekile. Sicela uthumele isixhumanisi se-Instagram esivumelekile.",
		"igDownloading":    "⏳ Ilanda okuqukethwe kwakho kwe-Instagram, sicela ulinde...",
		"igUploading":      "📤 Ilayisha ifayela lakho ku-Telegram...",
		"igSuccess":        "✅ Ukulanda kuphothuliwe!",
		"igError":          "❌ Ukulanda kwehlulekile. Iphosti ingase ibe yimfihlo noma ingatholakali.",
	},
	"am": {
		"welcome":          "እንኳን ወደ %s በደህና መጡ!\n\nእኔ ዘመናዊ የቴሌግራም ቦት ነኝ ከውስጥ ሜኑዎች፣ ሊበጁ ከሚችሉ ቅንብሮች እና ሌሎችም ጋር። ለመጀመር ከታች ያሉትን አዝራሮች ይጠቀሙ።\n\n👑 ባለቤት: %s",
		"help":             "እነዚህ ማድረግ የምችላቸው ነገሮች ናቸው:\n\n/start - ዋና ሜኑ አሳይ\n/help - ይህ የእርዳታ መልእክት\n/settings - የአጠቃቀም ልምድዎን ያብጁ\n/profile - መገለጫዎን ይመልከቱ\n/feedback - አስተያየት ይላኩልን\n/about - ስለዚህ ቦት ይረዱ\n/poll - ፈጣን ምርጫ ይፍጠሩ",
		"mainMenu":         "ዋና ሜኑ",
		"settings":         "⚙️ ቅንብሮች\n\nየአጠቃቀም ልምድዎን ያብጁ:",
		"languageChanged":  "ቋንቋ ወደ %s ተቀይሯል።",
		"profile":          "👤 የእርስዎ መገለጫ\n\nየተጠቃሚ መለያ: %d\nስም: %s\nቋንቋ: %s\nየተቀላቀሉት: %s",
		"feedbackPrompt":   "💬 አስተያየትዎን ይላኩ\n\nመልእክትዎን ከታች ይተይቡ። አስተያየትዎ እንድንሻሻል ይረዳናል!",
		"feedbackReceived": "✅ ለአስተያየትዎ እናመሰግናለን! እናደንቀዋለን።",
		"about":            "ℹ️ ስለ %s\n\nስሪት: %s\nመግለጫ: %s\n👑 ባለቤት: %s (%s)\n🕐 የሰዓት ሰቅ: %s\n\nበ❤️ የተሰራ Go እና go-telegram-bot-api በመጠቀም",
		"pollQuestion":     "📊 ለምርጫ ጥያቄ ይላኩልኝ:",
		"pollOptions":      "አማራጮችን ይላኩ፣ በአንድ መስመር አንድ (ቢያንስ 2፣ ቢበዛ 10):",
		"pollCreated":      "✅ ምርጫ ተፈጠረ!",
		"adminPanel":       "🔐 የአስተዳዳሪ ፓነል\n\nጠቅላላ ተጠቃሚዎች: %d\nጠቅላላ አስተያየቶች: %d",
		"noPermission":     "⛔ ይህን ትእዛዝ ለመጠቀም ፈቃድ የለዎትም።",
		"unknownCommand":   "የማይታወቅ ትእዛዝ። ያሉትን ትእዛዞች ለማየት /help ይጠቀሙ።",
		"backToMenu":       "« ወደ ዋና ሜኑ ተመለስ",
		"settingsMenu":     "⚙️ ቅንብሮች",
		"language":         "🌐 ቋንቋ",
		"notifications":    "🔔 ማሳወቂያዎች",
		"close":            "❌ ዝጋ",
		"selectLanguage":   "የሚመርጡትን ቋንቋ ይምረጡ:",
		"error":            "⚠️ ስህተት ተከስቷል። እባክዎ በኋላ እንደገና ይሞክሩ።",
		"processing":       "⏳ በማስኬድ ላይ...",
		"notifOnAlert":     "ማሳወቂያዎች ነቅተዋል",
		"notifOffAlert":    "ማሳወቂያዎች ጠፍተዋል",
		"notifStatus":      "ማሳወቂያዎች: %s",
		"notifEnabled":     "🔔 ነቅቷል",
		"notifDisabled":    "🔕 ጠፍቷል",
		"confirmAction":    "✅ ድርጊቱ ተረጋገጠ!",
		"cancelAction":     "❌ ድርጊቱ ተሰረዘ።",
		"confirmedAlert":   "ተረጋግጧል ✅",
		"cancelledAlert":   "ተሰርዟል ❌",
		"closedAlert":      "ተዘግቷል",
		"confirmed":        "✅ ተረጋገጠ!",
		"cancelled":        "❌ ተሰርዟል።",
		"ytPrompt":         "📥 ለማውረድ የYouTube ዩ.አር.ኤል ይላኩልኝ:",
		"ytInvalid":        "⚠️ ልክ ያልሆነ የYouTube ዩ.አር.ኤል። እባክዎ ልክ የሆነ የYouTube አገናኝ ይላኩ።",
		"ytFormat":         "🎯 ቅርጸት ይምረጡ:",
		"ytDownloading":    "⏳ ቪዲዮዎን በማውረድ ላይ፣ እባክዎ ይጠብቁ...",
		"ytUploading":      "📤 ፋይልዎን ወደ ቴሌግራም በመጫን ላይ...",
		"ytSuccess":        "✅ ማውረድ ተጠናቋል!",
		"ytError":          "❌ ማውረድ አልተሳካም። ቪዲዮው ላይገኝ ወይም የተገደበ ሊሆን ይችላል።",
		"ytFormatMp3":      "🎵 MP3 ኦዲዮ",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 ለማውረድ የInstagram ልጥፍ/ሪል ዩ.አር.ኤል ይላኩልኝ:",
		"igInvalid":        "⚠️ ልክ ያልሆነ የInstagram ዩ.አር.ኤል። እባክዎ ልክ የሆነ የInstagram አገናኝ ይላኩ።",
		"igDownloading":    "⏳ የInstagram ይዘትዎን በማውረድ ላይ፣ እባክዎ ይጠብቁ...",
		"igUploading":      "📤 ፋይልዎን ወደ ቴሌግራም በመጫን ላይ...",
		"igSuccess":        "✅ ማውረድ ተጠናቋል!",
		"igError":          "❌ ማውረድ አልተሳካም። ልጥፉ የግል ወይም ላይገኝ ይችላል።",
	},
	"af": {
		"welcome":          "Welkom by %s!\n\nEk is 'n moderne Telegram-bot met inlyn kieslyste, aanpasbare instellings, en meer. Gebruik die knoppies hieronder om te begin.\n\n👑 Eienaar: %s",
		"help":             "Hier is die dinge wat ek kan doen:\n\n/start - Wys hoofkieslys\n/help - Hierdie hulp boodskap\n/settings - Pas jou ervaring aan\n/profile - Bekyk jou profiel\n/feedback - Stuur vir ons terugvoer\n/about - Meer oor hierdie bot\n/poll - Skep 'n vinnige peiling",
		"mainMenu":         "Hoofkieslys",
		"settings":         "⚙️ Instellings\n\nPas jou ervaring aan:",
		"languageChanged":  "Taal verander na %s.",
		"profile":          "👤 Jou Profiel\n\nGebruiker ID: %d\nNaam: %s\nTaal: %s\nAangesluit: %s",
		"feedbackPrompt":   "💬 Stuur jou terugvoer\n\nTik jou boodskap hieronder. Jou terugvoer help ons om te verbeter!",
		"feedbackReceived": "✅ Dankie vir jou terugvoer! Ons waardeer dit.",
		"about":            "ℹ️ Oor %s\n\nWeergawe: %s\nBeskrywing: %s\n👑 Eienaar: %s (%s)\n🕐 Tydsone: %s\n\nGebou met ❤️ met Go en go-telegram-bot-api",
		"pollQuestion":     "📊 Stuur vir my 'n vraag vir die peiling:",
		"pollOptions":      "Stuur die opsies, een per lyn (min 2, maks 10):",
		"pollCreated":      "✅ Peiling geskep!",
		"adminPanel":       "🔐 Admin Paneel\n\nTotale gebruikers: %d\nTotale terugvoer: %d",
		"noPermission":     "⛔ Jy het nie toestemming om hierdie opdrag te gebruik nie.",
		"unknownCommand":   "Onbekende opdrag. Gebruik /help om beskikbare opdragte te sien.",
		"backToMenu":       "« Terug na Hoofkieslys",
		"settingsMenu":     "⚙️ Instellings",
		"language":         "🌐 Taal",
		"notifications":    "🔔 Kennisgewings",
		"close":            "❌ Maak toe",
		"selectLanguage":   "Kies jou voorkeurtaal:",
		"error":            "⚠️ 'n Fout het voorgekom. Probeer asseblief later weer.",
		"processing":       "⏳ Besig om te verwerk...",
		"notifOnAlert":     "Kennisgewings geaktiveer",
		"notifOffAlert":    "Kennisgewings gedeaktiveer",
		"notifStatus":      "Kennisgewings: %s",
		"notifEnabled":     "🔔 Geaktiveer",
		"notifDisabled":    "🔕 Gedeaktiveer",
		"confirmAction":    "✅ Aksie bevestig!",
		"cancelAction":     "❌ Aksie gekanselleer.",
		"confirmedAlert":   "Bevestig ✅",
		"cancelledAlert":   "Gekanselleer ❌",
		"closedAlert":      "Gesluit",
		"confirmed":        "✅ Bevestig!",
		"cancelled":        "❌ Gekanselleer.",
		"ytPrompt":         "📥 Stuur vir my 'n YouTube-URL om af te laai:",
		"ytInvalid":        "⚠️ Ongeldige YouTube-URL. Stuur asseblief 'n geldige YouTube-skakel.",
		"ytFormat":         "🎯 Kies formaat:",
		"ytDownloading":    "⏳ Laai jou video af, wag asseblief...",
		"ytUploading":      "📤 Laai jou lêer op na Telegram...",
		"ytSuccess":        "✅ Aflaai voltooi!",
		"ytError":          "❌ Aflaai misluk. Die video is dalk nie beskikbaar of beperk nie.",
		"ytFormatMp3":      "🎵 MP3-klank",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Stuur vir my 'n Instagram-plasing/Reel-URL om af te laai:",
		"igInvalid":        "⚠️ Ongeldige Instagram-URL. Stuur asseblief 'n geldige Instagram-skakel.",
		"igDownloading":    "⏳ Laai jou Instagram-inhoud af, wag asseblief...",
		"igUploading":      "📤 Laai jou lêer op na Telegram...",
		"igSuccess":        "✅ Aflaai voltooi!",
		"igError":          "❌ Aflaai misluk. Die plasing is dalk privaat of onbeskikbaar.",
	},
	"ig": {
		"welcome":          "Nnọọ na %s!\n\nAbụ m bot Telegram nke ọgbara ọhụrụ nwere menus inline, ntọala enwere ike ịhazi, na ihe ndị ọzọ. Jiri bọtịnụ ndị dị n'okpuru ibido.\n\n👑 Onye nwe: %s",
		"help":             "Ndị a bụ ihe m nwere ike ime:\n\n/start - Gosi menu isi\n/help - Ozi enyemaka a\n/settings - Hazie ahụmahụ gị\n/profile - Lelee profaịlụ gị\n/feedback - Zitere anyị nzaghachi\n/about - Mụta banyere bot a\n/poll - Mepụta ntuli aka ngwa ngwa",
		"mainMenu":         "Menu Isi",
		"settings":         "⚙️ Ntọala\n\nHazie ahụmahụ gị:",
		"languageChanged":  "Agbanwere asụsụ gaa na %s.",
		"profile":          "👤 Profaịlụ Gị\n\nID onye ọrụ: %d\nAha: %s\nAsụsụ: %s\nSonụrụ: %s",
		"feedbackPrompt":   "💬 Ziga nzaghachi gị\n\nTinye ozi gị n'okpuru. Nzaghachi gị na-enyere anyị aka imeziwanye!",
		"feedbackReceived": "✅ Daalụ maka nzaghachi gị! Anyị nwere ekele.",
		"about":            "ℹ️ Banyere %s\n\nỤdị: %s\nNkọwa: %s\n👑 Onye nwe: %s (%s)\n🕐 Mpaghara oge: %s\n\nEjiri ❤️ wuo ya site na Go na go-telegram-bot-api",
		"pollQuestion":     "📊 Zitere m ajụjụ maka ntuli aka:",
		"pollOptions":      "Ziga nhọrọ, otu n'ahịrị (ọ dịghị ihe na-erughị 2, karịa 10):",
		"pollCreated":      "✅ Emeela ntuli aka!",
		"adminPanel":       "🔐 Panel Ndị Nlekọta\n\nNgụkọta ndị ọrụ: %d\nNgụkọta nzaghachi: %d",
		"noPermission":     "⛔ Ị nweghị ikike iji iwu a.",
		"unknownCommand":   "Iwu amaghị. Jiri /help ịhụ iwu ndị dịnụ.",
		"backToMenu":       "« Laghachi na Menu Isi",
		"settingsMenu":     "⚙️ Ntọala",
		"language":         "🌐 Asụsụ",
		"notifications":    "🔔 Ọkwa",
		"close":            "❌ Mechie",
		"selectLanguage":   "Họrọ asụsụ ị masịrị:",
		"error":            "⚠️ Njehie mere. Biko nwaa ọzọ ma emechaa.",
		"processing":       "⏳ Ọ na-arụ ọrụ...",
		"notifOnAlert":     "Ọkwa gbanyụrụ",
		"notifOffAlert":    "Ọkwa gbanyụọ",
		"notifStatus":      "Ọkwa: %s",
		"notifEnabled":     "🔔 Gbanyụrụ",
		"notifDisabled":    "🔕 Gbanyụọ",
		"confirmAction":    "✅ Emeela nkwenye!",
		"cancelAction":     "❌ Akagbuola ihe ahụ.",
		"confirmedAlert":   "Ekwenyela ✅",
		"cancelledAlert":   "Akagbuola ❌",
		"closedAlert":      "Emechiela",
		"confirmed":        "✅ Ekwenyela!",
		"cancelled":        "❌ Akagbuola.",
		"ytPrompt":         "📥 Zitere m URL YouTube ka m budata:",
		"ytInvalid":        "⚠️ URL YouTube ezighi ezi. Biko ziga njikọ YouTube ziri ezi.",
		"ytFormat":         "🎯 Họrọ ụdị:",
		"ytDownloading":    "⏳ Na-ebudata vidiyo gị, biko chere...",
		"ytUploading":      "📤 Na-ebugo faịlụ gị na Telegram...",
		"ytSuccess":        "✅ Ebudatala!",
		"ytError":          "❌ Nbudata dara. Vidiyo nwere ike ọ nweghị ma ọ bụ amachibidoro ya.",
		"ytFormatMp3":      "🎵 Ọdịda MP3",
		"ytFormat360":      "🎬 MP4 360p",
		"ytFormat720":      "🎬 MP4 720p",
		"ytFormat1080":     "🎬 MP4 1080p",
		"igPrompt":         "📸 Zitere m URL Instagram post/reel ka m budata:",
		"igInvalid":        "⚠️ URL Instagram ezighi ezi. Biko ziga njikọ Instagram ziri ezi.",
		"igDownloading":    "⏳ Na-ebudata ọdịnaya Instagram gị, biko chere...",
		"igUploading":      "📤 Na-ebugo faịlụ gị na Telegram...",
		"igSuccess":        "✅ Ebudatala!",
		"igError":          "❌ Nbudata dara. Ozi nwere ike ịbụ nke nzuzo ma ọ bụ adịghị.",
	},
}

func Get(key, lang string, args ...interface{}) string {
	m, ok := strings[lang]
	if !ok {
		m = strings["en"]
	}
	val, ok := m[key]
	if !ok {
		val = strings["en"][key]
	}
	if len(args) > 0 {
		return fmt.Sprintf(val, args...)
	}
	return val
}

func SupportedLanguages() []string {
	var langs []string
	for l := range strings {
		langs = append(langs, l)
	}
	return langs
}

func LanguageName(lang string) string {
	names := map[string]string{
		"en": "English",
		"es": "Español",
		"fr": "Français",
		"de": "Deutsch",
		"hi": "हिन्दी",
		"ur": "اردو",
		"sw": "Kiswahili",
		"ha": "Hausa",
		"yo": "Yorùbá",
		"zu": "isiZulu",
		"am": "አማርኛ",
		"af": "Afrikaans",
		"ig": "Igbo",
	}
	if name, ok := names[lang]; ok {
		return name
	}
	return lang
}
